# Generated by Django 3.2.1 on 2021-05-07 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BedAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(db_index=True, max_length=1000)),
                ('district', models.CharField(db_index=True, max_length=500)),
                ('institution', models.CharField(db_index=True, max_length=500)),
                ('covid_beds_total', models.IntegerField(blank=True, null=True)),
                ('covid_beds_occupied', models.IntegerField(blank=True, null=True)),
                ('covid_beds_vacant', models.IntegerField(blank=True, null=True)),
                ('os_beds_total', models.IntegerField(blank=True, null=True, verbose_name='oxygen supported beds total')),
                ('os_beds_occupied', models.IntegerField(blank=True, null=True, verbose_name='oxygen supported beds occupied')),
                ('os_beds_vacant', models.IntegerField(blank=True, null=True, verbose_name='oxygen supported beds vacant')),
                ('nos_beds_total', models.IntegerField(blank=True, null=True, verbose_name='non-oxygen supported beds total')),
                ('nos_beds_occupied', models.IntegerField(blank=True, null=True, verbose_name='non-oxygen supported beds occupied')),
                ('nos_beds_vacant', models.IntegerField(blank=True, null=True, verbose_name='non-oxygen supported beds vacant')),
                ('icu_beds_total', models.IntegerField(blank=True, null=True, verbose_name='ICU beds total')),
                ('icu_beds_occupied', models.IntegerField(blank=True, null=True, verbose_name='ICU beds occupied')),
                ('icu_beds_vacant', models.IntegerField(blank=True, null=True, verbose_name='ICU beds vacant')),
                ('ventilators_total', models.IntegerField(blank=True, null=True)),
                ('ventilators_occupied', models.IntegerField(blank=True, null=True)),
                ('ventilators_vacant', models.IntegerField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('contact_number', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('meta_synced_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('meta_last_updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('meta_created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name_plural': 'bed availabilities',
            },
        ),
        migrations.CreateModel(
            name='BedAvailabilityCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(db_index=True, max_length=1000)),
                ('district', models.CharField(db_index=True, max_length=500)),
                ('institution', models.CharField(db_index=True, max_length=500)),
                ('covid_beds_total', models.IntegerField(blank=True, null=True)),
                ('covid_beds_occupied', models.IntegerField(blank=True, null=True)),
                ('covid_beds_vacant', models.IntegerField(blank=True, null=True)),
                ('os_beds_total', models.IntegerField(blank=True, null=True, verbose_name='oxygen supported beds total')),
                ('os_beds_occupied', models.IntegerField(blank=True, null=True, verbose_name='oxygen supported beds occupied')),
                ('os_beds_vacant', models.IntegerField(blank=True, null=True, verbose_name='oxygen supported beds vacant')),
                ('nos_beds_total', models.IntegerField(blank=True, null=True, verbose_name='non-oxygen supported beds total')),
                ('nos_beds_occupied', models.IntegerField(blank=True, null=True, verbose_name='non-oxygen supported beds occupied')),
                ('nos_beds_vacant', models.IntegerField(blank=True, null=True, verbose_name='non-oxygen supported beds vacant')),
                ('icu_beds_total', models.IntegerField(blank=True, null=True, verbose_name='ICU beds total')),
                ('icu_beds_occupied', models.IntegerField(blank=True, null=True, verbose_name='ICU beds occupied')),
                ('icu_beds_vacant', models.IntegerField(blank=True, null=True, verbose_name='ICU beds vacant')),
                ('ventilators_total', models.IntegerField(blank=True, null=True)),
                ('ventilators_occupied', models.IntegerField(blank=True, null=True)),
                ('ventilators_vacant', models.IntegerField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('contact_number', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('meta_synced_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('meta_last_updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('meta_created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SyncPull',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('beds_info', models.JSONField(default=dict)),
                ('meta', models.JSONField(default=dict)),
            ],
        ),
    ]
